require 'hashmake'

require 'music-instruments/version'
require 'music-instruments/limits/enum_limit'
require 'music-instruments/limits/lower_limit'
require 'music-instruments/limits/no_limit'
require 'music-instruments/limits/range_limit'
require 'music-instruments/limits/upper_limit'
require 'music-instruments/parameter'
require 'music-instruments/instrument_key'
require 'music-instruments/instrument'
